"""Items for the "judge" tier (judging whether the answer to a math problem is correct),
with exact labels: solutions generated by a small model (natural errors) + clean reference
solutions, checked against the GSM8K gold answers (MIT license).

usage: python prog_judge.py <generator_model> <cuda:N> <out.jsonl> [n_problems]
"""
from __future__ import annotations

import json
import random
import re
import sys

import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

GEN, DEV, OUT = sys.argv[1], sys.argv[2], sys.argv[3]
NMAX = int(sys.argv[4]) if len(sys.argv) > 4 else 100000
rng = random.Random(3)

ds = load_dataset("openai/gsm8k", "main")["train"]
probs = [(r["question"], r["answer"]) for r in ds][:NMAX]


def gold_num(ans):
    return ans.split("####")[-1].strip().replace(",", "")


def clean_ref(ans):
    body = ans.split("####")[0]
    body = re.sub(r"<<[^>]*>>", "", body).strip()
    return body


def to_num(s):
    try:
        return float(s.replace(",", "").replace("$", "").strip().rstrip("."))
    except Exception:  # noqa: BLE001
        return None


tok = AutoTokenizer.from_pretrained(GEN)
tok.padding_side = "left"
model = AutoModelForCausalLM.from_pretrained(GEN, dtype=torch.bfloat16, device_map={"": DEV}).eval()

PROMPT = ("Solve the problem step by step in a few short lines, then write the last line exactly as "
          "'Final answer: <number>'.\n\nProblem: {q}")
sols = []
B = 48
for b in range(0, len(probs), B):
    chunk = probs[b:b + B]
    texts = [tok.apply_chat_template([{"role": "user", "content": PROMPT.format(q=q)}], tokenize=False,
                                     add_generation_prompt=True, enable_thinking=False) for q, _ in chunk]
    enc = tok(texts, return_tensors="pt", padding=True, add_special_tokens=False).to(DEV)
    with torch.no_grad():
        out = model.generate(**enc, max_new_tokens=320, do_sample=True, temperature=0.8, top_p=0.95)
    for (q, a), o in zip(chunk, out):
        txt = tok.decode(o[enc["input_ids"].shape[1]:], skip_special_tokens=True).strip()
        m = re.search(r"Final answer:\s*\$?\s*([-\d.,]+)", txt)
        sols.append((q, a, txt, m.group(1).rstrip(".") if m else None))
    print(f"{min(b + B, len(probs))}/{len(probs)}", flush=True)

CRIT = {"true": "The proposed final answer is the correct answer to the problem.",
        "false": "The proposed final answer is not the correct answer to the problem."}
n_ok = n_bad = 0
with open(OUT, "w") as f:
    for i, (q, a, txt, pred) in enumerate(sols):
        g = to_num(gold_num(a))
        p = to_num(pred) if pred else None
        if g is None or p is None:
            continue
        correct = abs(p - g) < 1e-6
        # balance: model solutions (correct/wrong) + clean reference (correct) when there are too few errors
        if correct and rng.random() < 0.5 and n_ok > n_bad:
            continue
        variant = rng.random()
        body = txt.split("Final answer:")[0].strip()
        if variant < 0.3:
            state = f"Problem:\n{q}\n\nProposed final answer: {pred}"
        else:
            state = f"Problem:\n{q}\n\nProposed solution:\n{body}\n\nProposed final answer: {pred}"
        lab = "yes" if correct else "no"
        rec = {"id": f"prog-judge-{i:05d}", "family": "judge", "topic": "math & numbers", "state": state,
               "question": {"type": "noul", "instructions": "Is the proposed final answer correct?", "criteria": CRIT},
               "labels": ["no", "yes"], "expected": lab,
               "teacher_probs": {"yes": 0.97 if correct else 0.03, "no": 0.03 if correct else 0.97},
               "teacher_top": lab, "agree": True, "difficulty": "standard", "lang": "English",
               "source": "prog_judge:gsm8k_model"}
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")
        n_ok += int(correct)
        n_bad += int(not correct)
        if not correct and rng.random() < 0.6:
            ref = clean_ref(a)
            state = f"Problem:\n{q}\n\nProposed solution:\n{ref}\n\nProposed final answer: {gold_num(a)}"
            rec = dict(rec, id=f"prog-judge-ref-{i:05d}", state=state, expected="yes",
                       teacher_probs={"yes": 0.97, "no": 0.03}, teacher_top="yes", source="prog_judge:gsm8k_ref")
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
            n_ok += 1
print("DONE", {"correct": n_ok, "wrong": n_bad}, flush=True)
